name: "Publish Go Package"

# The workflow below runs when the release event triggers with the created release type.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)
# See: https://github.com/marketplace/actions/build-and-push-docker-images

on:
  release:
    types:
      - created

jobs:
  releases-super-config:
    name: "Release Go Binary"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
    # See: https://github.com/marketplace/actions/checkout
    - name: "Checkout repository"
      id: checkout_repository
      uses: actions/checkout@v3

    # See: https://github.com/marketplace/actions/go-release-binaries
    - name: "Publish go package"
      uses: wangyoucao577/go-release-action@v1.21
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.19
        project_path: "."
        binary_name: "super-config"
        extra_files: LICENSE README.md
